### ISSUE TITLE
Bild 65 wird nicht angezeigt (small-team-flow.png)

### ISSUE THREAD

**Issue by saxc** [progit/progit2-de#101]
Bild 65 (small-team-flow.png) wird nicht angezeigt.
book\05-distributed-git\sections\contributing.asc

Verglichen wurde deutsche Version 2.1.80 mit der Englischen V2.1.255.

Aufgefallen ist dies in den PDFs (oben angegebene Version) und in einer etwas älteren V2.1.7x MOBI Version.

![missing_picture](https://user-images.githubusercontent.com/7613585/82234989-70511d00-9932-11ea-83b4-3e520345fa01.png)

**Comment by max123kl** [comment]
Sobald das neue Release geschrieben ist, sollte die Abbildung im PDF, u.a. erscheinen.
Auf der Website dauert es meistens etwas länger.

**Comment by max123kl** [comment]
Resolved
