### ISSUE TITLE
Schlechtes Wording: "Optionen haben Optionen"

### ISSUE THREAD

**Issue by Mo-Gul** [progit/progit2-de#120]
siehe Diskussion in PR #117.

**Comment by Mo-Gul** [comment]
Danke @cbachhuber für https://github.com/progit/progit2/pull/1457.

Bist du auch motiviert direkt einen PR für die deutsche Fassung zu formulieren?

**Comment by cbachhuber** [comment]
Gerne! Den entsprechenden PR in diesem Repo kann ich am Wochenende gerne machen.

**Comment by cbachhuber** [comment]
In #128 von @max123kl gelöst
