### ISSUE TITLE
Direct pushes to main not allowed

### ISSUE THREAD

**Issue by pastatopf** [progit/progit2-de#376]
### General overview of your idea.

@jnavila : Could you please add to the main branch of this repository the protection rule to Require a pull request before merging?
It seems that I don't have the permissions.

### What problem will this solve?

Direct pushes to main

### Do you want to help with this enhancement idea?

Yes

**Comment by pastatopf** [comment]
Unfortunately I'm still able commit to main

**Comment by jnavila** [comment]
I add required pull request. This should be good now.

**Comment by pastatopf** [comment]
Thanks for that.
But now new builds on main  are failing. It seems that the pipeline is not generating a new Tag in the build now.
Could you please check?
If it will take you too much time we can leave it as it is. Should not be a bigger problem.

**Comment by pastatopf** [comment]
Works again
