### ISSUE TITLE
Korrektur von Siezen Artefakten in 6.2

### ISSUE THREAD

**Issue by DonnerWolfBach** [progit/progit2-de#406]
Von #373 scheinen ein paar Artefakte übrig geblieben zu sein über die ich gestolpert bin und die ich direkt korrigieren möchte.

**Comment by pastatopf** [comment]
Sehr gerne, aber ich glaube ich bin jetzt komplett durch. 
Oder ist noch irgendwo die Sie Form vorhanden?

**Comment by DonnerWolfBach** [comment]
siehe #407, habe vergessen das Github keinen Button hat um direkt einen branch und merge request zu erstellen
