### ISSUE TITLE
Übersetzung von 'String'

### ISSUE THREAD

**Issue by cbachhuber** [progit/progit2-de#49]
Während ich ich PR #48 erstellt habe, habe ich festgestellt dass in den [translation notes](https://github.com/progit/progit2-de/blob/master/TRANSLATION_NOTES_DE.asc) keine Vorgabe zur Übersetzung von `String` gemacht wird. 

In den translation notes wird das Wort `String` im Deutschen verwendet, allerdings ist es nicht in den Tabellen definiert. In der Übersetzung des Buches dagegen wird `Zeichenkette` verwendet, siehe z.B. in der [Einleitung](https://github.com/progit/progit2-de/blob/master/book/01-introduction/sections/what-is-git.asc#git-stellt-integrit%C3%A4t-sicher).

Ich schlage vor dass wir uns auf eine Schreibweise einigen, diese in den translation notes dokumentieren und konsistent nutzen. Obwohl kaum jemand das Wort Zeichenkette benutzt, bevorzuge ich dieses Wort, da es im Gegensatz zu String selbsterklärend ist. Was meint ihr?

**Comment by pastatopf** [comment]
Ja, passt. Gerne können wir uns auf Zeichenkette einigen. Ich denke beides würde gut passen, aber es soll ja schliesslich die deutsche Übersetzung sein. 
Kannst du es in die translation notes noch einfügen?

**Comment by max123kl** [comment]
Wie ich in meinem [Kommentar](url) schon angemerkt hatte, finde ich, dass der engl. Begriff durchaus neben dem dt. Begriff existieren darf.
in der TRANSLATION_NOTES_DE.asc z.B.  
string --> Zeichenkette, alternativ auch String möglich

**Comment by cbachhuber** [comment]
Beide existieren zu lassen finde ich gut!

Ich passe die translation notes heute noch in #48 an.
