### ISSUE TITLE
Projekt um offene bzw. in Arbeit befindliche Übersetzungen zu tracken

### ISSUE THREAD

**Issue by pastatopf** [progit/progit2-de#57]
Hallo Zusammen,

ich habe [hier ](https://github.com/progit/progit2-de/projects/1) ein Projekt erstellt mit einem einfachen Kanbaan Board, um zu tracken, welche Dateien noch übersetzt werden müssen und welche Dateien sich gerade von wem in Übersetzung befinden.
Was haltet ihr davon?

Gruß
Oscar

**Comment by max123kl** [comment]
Die Übersicht finde ich gut.
Ich war gestern nahe dran dich per e-mail über meine weitere Arbeit zu informieren.
Das ist die bessere Lösung.
Mir fehlt nur, dass man schon auf der Karte erkennen kann, wer die Datei in Arbeit hat. Ist das machbar?

**Comment by pastatopf** [comment]
Man kann die Karten editieren (siehe screenshot). Ich hab eine editiert und deinen Namen rein geschrieben. Kannst du das auch?
![image](https://user-images.githubusercontent.com/6805462/71877246-f65d8b80-3128-11ea-9fe6-cb92025ee559.png)

**Comment by max123kl** [comment]
Editiert hatte ich schon bei der Karte darunter.
Könnte man die Karte ev. einfärben, je nach Priorität oder anderer Kriterien?

**Comment by pastatopf** [comment]
In dem aktuellen Projekt so nicht. Ich hab als Projekttyp das ganz rudimentäre Kanbaan Board genommen. Eventuell gehts mit anderen Projekttypen.
Meinst du wir brauchen das? Ich würde eher drauf verzichten, ist ja nicht mehr viel. :-)

**Comment by pastatopf** [comment]
@cbachhuber : Arbeitest du eventuell auch an einer Übersetzung? Kannst du mal schauen, ob du das Kanban Board bearbeiten kannst?

**Comment by cbachhuber** [comment]
Das finde ich eine super Idee!

Leider kann ich im Moment nichts am Kanban Board bearbeiten. Ich kann die Karten nicht ziehen und wenn ich auf die drei Punkte bei einer Karte klicke, bekomme ich nur die Option "Copy card link". Natürlich soll das Board nicht von jedem Github-Mitglied modifizierbar sein. Gibt es die Einstellung, dass die Gruppe der Leute, die schon zu diesem Repository beigetragen haben, das Board modifizieren können? Dann müsste man nur bei seinem ersten PR in diesem Repo dich oder @max123kl das Board anzupassen.

**Comment by pastatopf** [comment]
Ich kann leider keine Berechtigungen vergeben, da das Repo nicht mir gehört.
Ich hab mal an eins meiner Repos getestet und dir eine Einladung geschickt, um dich als Collaborator aufzunehmen, um zu sehen, was ich überhaupt für Berechtigungen vergeben kann. Kannst du die mal annehmen?
Damit könnte ich dann bei den Repo Ownern nachfragen, ob sie dir die entsprechenden Permissions geben können.

**Comment by max123kl** [comment]
@cbachhuber 
Ich habe auch nur die gleichen Rechte wie pastatopf

**Comment by cbachhuber** [comment]
> Ich hab mal an eins meiner Repos getestet und dir eine Einladung geschickt, um dich als Collaborator aufzunehmen, um zu sehen, was ich überhaupt für Berechtigungen vergeben kann. Kannst du die mal annehmen?

Habs angenommen, bin gespannt welche Rechte kommen ;)

**Comment by pastatopf** [comment]
@cbachhuber : Ich kann gar keine Reche vergeben, sondern dich nur als Collaborator eintragen, also Pustekuchen... :-)

Dann lassen wir es so und machen es einfach auf Anfrage. Bist du an irgend welchen Kapiteln dran? Dann setze ich das auf dem Kanban Board um.

**Comment by cbachhuber** [comment]
Alles klar, ich finde das immer noch gut :)

Im Moment übersetze ich nichts, ich melde mich wenn ich wieder Zeit finde.

**Comment by pastatopf** [comment]
Issue wird geschlossen, da die übersetzung abgeschlossen ist.
