### ISSUE TITLE
Release runs are not executed

### ISSUE THREAD

**Issue by pastatopf** [progit/progit2-de#60]
@jnavila : Could you have a look at the travis config of our repo?

Some days ago I adapted the travis config in our project because Travis CI was failing. After my changes it worked.

But now the Releases are not created automatically as before. Can you please have a look if I'm missing something?

Thanks

**Comment by jnavila** [comment]
You should revert the changes to `.travis`, they embedded the necessary scripting for managing releases.

**Comment by jnavila** [comment]
The upgrade of the Gemfile must be performed in the project progit/progit2-pub. I'll do it today.

**Comment by jnavila** [comment]
The main build scripts are fixed. You can revert the `.travis` file.

**Comment by pastatopf** [comment]
Thanks it works now.
